### ISSUE TITLE
All unit tests fail

### ISSUE THREAD

**Issue by bahmutov** [dtao/htmlout#1]
with the following error in jsdom

```
  13) htmlout can apply the text-transform property:
     TypeError: Cannot set property length of [object Object] which has only a getter
    at [object Object].core.Node.insertBefore (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/jsdom/lib/jsdom/level1/core.js:553:30)
    at [object Object].<anonymous> (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/jsdom/lib/jsdom/level2/events.js:332:20)
    at [object Object].proto.(anonymous function) [as insertBefore] (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/jsdom/lib/jsdom/utils.js:23:26)
    at [object Object].core.Node.appendChild (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/jsdom/lib/jsdom/level1/core.js:671:17)
    at [object Object].textContent (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/jsdom/lib/jsdom/level3/core.js:187:10)
    at /Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/htmlout.js:100:27
    at Array.forEach (native)
    at htmlout (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/htmlout.js:98:15)
    at getOutput (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/test/htmlout_test.coffee:11:3)
    at Context.<anonymous> (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/test/htmlout_test.coffee:165:5)
    at Test.Runnable.run (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/mocha/lib/runnable.js:221:32)
    at Runner.runTest (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/mocha/lib/runner.js:374:10)
    at /Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/mocha/lib/runner.js:452:12
    at next (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/mocha/lib/runner.js:299:14)
    at /Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/mocha/lib/runner.js:309:7
    at next (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/mocha/lib/runner.js:247:23)
    at Immediate._onImmediate (/Users/gleb/git/training/js/test-htmlout/node_modules/htmlout/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by dtao** [comment]
Oh dear. Shame on whoever maintains this repo... oh wait, that's me.

I'll try to take a look in the next few days.

**Comment by philkunz** [comment]
Hi, any chance you implement a fix? Because the idea is awesome!

**Comment by ghost** [comment]
+1, 
This would be excellent!
