### ISSUE TITLE
Contextify fails with wtf???

### ISSUE THREAD

**Issue by LoganDark** [dtao/htmlout#2]
```
LoganDark:~/node-selfbot> npm install htmlout

> contextify@0.1.15 install /Users/LoganDark/node-selfbot/node_modules/contextify
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:131:56: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                       ^
/Users/LoganDark/.node-gyp/7.5.0/include/node/v8.h:3292:52: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:182:51: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                  ^
/Users/LoganDark/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:209:38: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                     ^
/Users/LoganDark/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:210:42: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                         ^
/Users/LoganDark/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/LoganDark/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Users/LoganDark/.nvm/versions/node/v7.5.0/bin/node" "/Users/LoganDark/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/LoganDark/node-selfbot/node_modules/contextify
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN discord.js@11.0.0 requires a peer of uws@^0.12.0 but none was installed.
npm WARN logandark-selfbot@1.0.0 No repository field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/LoganDark/.nvm/versions/node/v7.5.0/bin/node" "/Users/LoganDark/.nvm/versions/node/v7.5.0/bin/npm" "install" "contextify"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/LoganDark/node-selfbot/npm-debug.log
LoganDark:~/node-selfbot> cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/Users/LoganDark/.nvm/versions/node/v7.5.0/bin/node',
1 verbose cli   '/Users/LoganDark/.nvm/versions/node/v7.5.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'contextify' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData contextify
8 silly fetchNamedPackageData contextify
9 silly mapToRegistry name contextify
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'contextify',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'contextify',
12 silly mapToRegistry   name: 'contextify',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/contextify
14 verbose request uri https://registry.npmjs.org/contextify
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:29:51 PM
17 verbose request using bearer token for auth
18 verbose request id 5c99249a081e4854
19 verbose etag W/"5644b79b-942b"
20 verbose lastModified Thu, 12 Nov 2015 16:00:27 GMT
21 http request GET https://registry.npmjs.org/contextify
22 http 304 https://registry.npmjs.org/contextify
23 verbose headers { server: 'nginx/1.10.1',
23 verbose headers   'last-modified': 'Thu, 12 Nov 2015 16:00:27 GMT',
23 verbose headers   etag: '"5644b79b-942b"',
23 verbose headers   'cache-control': 'max-age=300',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Tue, 21 Feb 2017 02:29:52 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-sea1046-SEA',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1487644192.496824,VS0,VE67',
23 verbose headers   vary: 'Accept-Encoding' }
24 silly get cb [ 304,
24 silly get   { server: 'nginx/1.10.1',
24 silly get     'last-modified': 'Thu, 12 Nov 2015 16:00:27 GMT',
24 silly get     etag: '"5644b79b-942b"',
24 silly get     'cache-control': 'max-age=300',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Tue, 21 Feb 2017 02:29:52 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-sea1046-SEA',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1487644192.496824,VS0,VE67',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose etag https://registry.npmjs.org/contextify from cache
26 verbose get saving contextify to /Users/LoganDark/.npm/registry.npmjs.org/contextify/.cache.json
27 verbose correctMkdir /Users/LoganDark/.npm correctMkdir not in flight; initializing
28 silly install normalizeTree
29 silly loadCurrentTree Finishing
30 silly loadIdealTree Starting
31 silly install loadIdealTree
32 silly cloneCurrentTree Starting
33 silly install cloneCurrentTreeToIdealTree
34 silly cloneCurrentTree Finishing
35 silly loadShrinkwrap Starting
36 silly install loadShrinkwrap
37 silly loadShrinkwrap Finishing
38 silly loadAllDepsIntoIdealTree Starting
39 silly install loadAllDepsIntoIdealTree
40 silly resolveWithNewModule contextify@0.1.15 checking installable status
41 silly cache add args [ 'contextify', null ]
42 verbose cache add spec contextify
43 silly cache add parsed spec Result {
43 silly cache add   raw: 'contextify',
43 silly cache add   scope: null,
43 silly cache add   escapedName: 'contextify',
43 silly cache add   name: 'contextify',
43 silly cache add   rawSpec: '',
43 silly cache add   spec: 'latest',
43 silly cache add   type: 'tag' }
44 silly addNamed contextify@latest
45 verbose addNamed "latest" is being treated as a dist-tag for contextify
46 info addNameTag [ 'contextify', 'latest' ]
47 silly mapToRegistry name contextify
48 silly mapToRegistry using default registry
49 silly mapToRegistry registry https://registry.npmjs.org/
50 silly mapToRegistry data Result {
50 silly mapToRegistry   raw: 'contextify',
50 silly mapToRegistry   scope: null,
50 silly mapToRegistry   escapedName: 'contextify',
50 silly mapToRegistry   name: 'contextify',
50 silly mapToRegistry   rawSpec: '',
50 silly mapToRegistry   spec: 'latest',
50 silly mapToRegistry   type: 'tag' }
51 silly mapToRegistry uri https://registry.npmjs.org/contextify
52 verbose addNameTag registry:https://registry.npmjs.org/contextify not in flight; fetching
53 verbose get https://registry.npmjs.org/contextify not expired, no request
54 silly addNameTag next cb for contextify with tag latest
55 silly addNamed contextify@0.1.15
56 verbose addNamed "0.1.15" is a plain semver version for contextify
57 silly cache afterAdd contextify@0.1.15
58 verbose afterAdd /Users/LoganDark/.npm/contextify/0.1.15/package/package.json not in flight; writing
59 verbose correctMkdir /Users/LoganDark/.npm correctMkdir not in flight; initializing
60 verbose afterAdd /Users/LoganDark/.npm/contextify/0.1.15/package/package.json written
61 silly loadAllDepsIntoIdealTree Finishing
62 silly loadIdealTree Finishing
63 silly currentTree logandark-selfbot@1.0.0
63 silly currentTree ├── @types/node@6.0.63
63 silly currentTree ├── ansi-regex@2.1.1
63 silly currentTree ├── ansi-styles@2.2.1
63 silly currentTree ├── asn1@0.2.3
63 silly currentTree ├── assert-plus@0.2.0
63 silly currentTree ├── asynckit@0.4.0
63 silly currentTree ├── aws-sign2@0.6.0
63 silly currentTree ├── aws4@1.6.0
63 silly currentTree ├── bcrypt-pbkdf@1.0.1
63 silly currentTree ├── bindings@1.2.1
63 silly currentTree ├── boom@2.10.1
63 silly currentTree ├── buffer-shims@1.0.0
63 silly currentTree ├── caseless@0.11.0
63 silly currentTree ├── chalk@1.1.3
63 silly currentTree ├── cli-clear@1.0.4
63 silly currentTree ├── combined-stream@1.0.5
63 silly currentTree ├── commander@2.9.0
63 silly currentTree ├── component-emitter@1.2.1
63 silly currentTree ├── cookiejar@2.1.0
63 silly currentTree ├── core-util-is@1.0.2
63 silly currentTree ├── cryptiles@2.0.5
63 silly currentTree ├── cssom@0.3.2
63 silly currentTree ├── cssstyle@0.2.37
63 silly currentTree ├─┬ dashdash@1.14.1
63 silly currentTree │ └── assert-plus@1.0.0
63 silly currentTree ├── debug@2.6.1
63 silly currentTree ├── delayed-stream@1.0.0
63 silly currentTree ├── discord.js@11.0.0
63 silly currentTree ├─┬ dom-serializer@0.1.0
63 silly currentTree │ └── domelementtype@1.1.3
63 silly currentTree ├── domelementtype@1.3.0
63 silly currentTree ├── domhandler@2.3.0
63 silly currentTree ├── domutils@1.5.1
63 silly currentTree ├── ecc-jsbn@0.1.1
63 silly currentTree ├── entities@1.1.1
63 silly currentTree ├── erlpack@0.1.0
63 silly currentTree ├── escape-string-regexp@1.0.5
63 silly currentTree ├── extend@3.0.0
63 silly currentTree ├── extsprintf@1.0.2
63 silly currentTree ├── forever-agent@0.6.1
63 silly currentTree ├── form-data@2.1.2
63 silly currentTree ├── formidable@1.1.1
63 silly currentTree ├── generate-function@2.0.0
63 silly currentTree ├── generate-object-property@1.2.0
63 silly currentTree ├─┬ getpass@0.1.6
63 silly currentTree │ └── assert-plus@1.0.0
63 silly currentTree ├── graceful-readlink@1.0.1
63 silly currentTree ├── har-validator@2.0.6
63 silly currentTree ├── has-ansi@2.0.0
63 silly currentTree ├── hawk@3.1.3
63 silly currentTree ├── highlight.js@9.9.0
63 silly currentTree ├── hoek@2.16.3
63 silly currentTree ├── htmlparser2@3.9.2
63 silly currentTree ├── http-signature@1.1.1
63 silly currentTree ├── inherits@2.0.3
63 silly currentTree ├── is-my-json-valid@2.15.0
63 silly currentTree ├── is-property@1.0.2
63 silly currentTree ├── is-typedarray@1.0.0
63 silly currentTree ├── isarray@1.0.0
63 silly currentTree ├── isstream@0.1.2
63 silly currentTree ├── jodid25519@1.0.2
63 silly currentTree ├── jsbn@0.1.1
63 silly currentTree ├── json-schema@0.2.3
63 silly currentTree ├── json-stringify-safe@5.0.1
63 silly currentTree ├── jsonpointer@4.0.1
63 silly currentTree ├── jsprim@1.3.1
63 silly currentTree ├── methods@1.1.2
63 silly currentTree ├── mime-db@1.26.0
63 silly currentTree ├── mime-types@2.1.14
63 silly currentTree ├── mime@1.3.4
63 silly currentTree ├── moment@2.17.1
63 silly currentTree ├── ms@0.7.2
63 silly currentTree ├── nan@2.5.1
63 silly currentTree ├── nearest-color@0.3.1
63 silly currentTree ├── node-opus@0.2.4
63 silly currentTree ├── nwmatcher@1.3.9
63 silly currentTree ├── oauth-sign@0.8.2
63 silly currentTree ├── ogg-packet@1.0.0
63 silly currentTree ├── options@0.0.6
63 silly currentTree ├── opusscript@0.0.1
63 silly currentTree ├── pako@1.0.4
63 silly currentTree ├── pinkie-promise@2.0.1
63 silly currentTree ├── pinkie@2.0.4
63 silly currentTree ├── process-nextick-args@1.0.7
63 silly currentTree ├── punycode@1.4.1
63 silly currentTree ├── qs@6.3.1
63 silly currentTree ├── readable-stream@2.2.2
63 silly currentTree ├── ref-struct@1.1.0
63 silly currentTree ├── ref@1.3.4
63 silly currentTree ├── request@2.79.0
63 silly currentTree ├── sntp@1.0.9
63 silly currentTree ├─┬ sshpk@1.10.2
63 silly currentTree │ └── assert-plus@1.0.0
63 silly currentTree ├── string_decoder@0.10.31
63 silly currentTree ├── stringstream@0.0.5
63 silly currentTree ├── strip-ansi@3.0.1
63 silly currentTree ├── superagent@3.4.4
63 silly currentTree ├── supports-color@2.0.0
63 silly currentTree ├── tough-cookie@2.3.2
63 silly currentTree ├── tunnel-agent@0.4.3
63 silly currentTree ├── tweetnacl@0.14.5
63 silly currentTree ├── ultron@1.0.2
63 silly currentTree ├── util-deprecate@1.0.2
63 silly currentTree ├── uuid@3.0.1
63 silly currentTree ├── verror@1.3.6
63 silly currentTree ├── writer.js@0.1.0
63 silly currentTree ├── ws@1.1.2
63 silly currentTree ├── xmlhttprequest@1.8.0
63 silly currentTree └── xtend@4.0.1
64 silly idealTree logandark-selfbot@1.0.0
64 silly idealTree ├── @types/node@6.0.63
64 silly idealTree ├── ansi-regex@2.1.1
64 silly idealTree ├── ansi-styles@2.2.1
64 silly idealTree ├── asn1@0.2.3
64 silly idealTree ├── assert-plus@0.2.0
64 silly idealTree ├── asynckit@0.4.0
64 silly idealTree ├── aws-sign2@0.6.0
64 silly idealTree ├── aws4@1.6.0
64 silly idealTree ├── bcrypt-pbkdf@1.0.1
64 silly idealTree ├── bindings@1.2.1
64 silly idealTree ├── boom@2.10.1
64 silly idealTree ├── buffer-shims@1.0.0
64 silly idealTree ├── caseless@0.11.0
64 silly idealTree ├── chalk@1.1.3
64 silly idealTree ├── cli-clear@1.0.4
64 silly idealTree ├── combined-stream@1.0.5
64 silly idealTree ├── commander@2.9.0
64 silly idealTree ├── component-emitter@1.2.1
64 silly idealTree ├── contextify@0.1.15
64 silly idealTree ├── cookiejar@2.1.0
64 silly idealTree ├── core-util-is@1.0.2
64 silly idealTree ├── cryptiles@2.0.5
64 silly idealTree ├── cssom@0.3.2
64 silly idealTree ├── cssstyle@0.2.37
64 silly idealTree ├─┬ dashdash@1.14.1
64 silly idealTree │ └── assert-plus@1.0.0
64 silly idealTree ├── debug@2.6.1
64 silly idealTree ├── delayed-stream@1.0.0
64 silly idealTree ├── discord.js@11.0.0
64 silly idealTree ├─┬ dom-serializer@0.1.0
64 silly idealTree │ └── domelementtype@1.1.3
64 silly idealTree ├── domelementtype@1.3.0
64 silly idealTree ├── domhandler@2.3.0
64 silly idealTree ├── domutils@1.5.1
64 silly idealTree ├── ecc-jsbn@0.1.1
64 silly idealTree ├── entities@1.1.1
64 silly idealTree ├── erlpack@0.1.0
64 silly idealTree ├── escape-string-regexp@1.0.5
64 silly idealTree ├── extend@3.0.0
64 silly idealTree ├── extsprintf@1.0.2
64 silly idealTree ├── forever-agent@0.6.1
64 silly idealTree ├── form-data@2.1.2
64 silly idealTree ├── formidable@1.1.1
64 silly idealTree ├── generate-function@2.0.0
64 silly idealTree ├── generate-object-property@1.2.0
64 silly idealTree ├─┬ getpass@0.1.6
64 silly idealTree │ └── assert-plus@1.0.0
64 silly idealTree ├── graceful-readlink@1.0.1
64 silly idealTree ├── har-validator@2.0.6
64 silly idealTree ├── has-ansi@2.0.0
64 silly idealTree ├── hawk@3.1.3
64 silly idealTree ├── highlight.js@9.9.0
64 silly idealTree ├── hoek@2.16.3
64 silly idealTree ├── htmlparser2@3.9.2
64 silly idealTree ├── http-signature@1.1.1
64 silly idealTree ├── inherits@2.0.3
64 silly idealTree ├── is-my-json-valid@2.15.0
64 silly idealTree ├── is-property@1.0.2
64 silly idealTree ├── is-typedarray@1.0.0
64 silly idealTree ├── isarray@1.0.0
64 silly idealTree ├── isstream@0.1.2
64 silly idealTree ├── jodid25519@1.0.2
64 silly idealTree ├── jsbn@0.1.1
64 silly idealTree ├── json-schema@0.2.3
64 silly idealTree ├── json-stringify-safe@5.0.1
64 silly idealTree ├── jsonpointer@4.0.1
64 silly idealTree ├── jsprim@1.3.1
64 silly idealTree ├── methods@1.1.2
64 silly idealTree ├── mime-db@1.26.0
64 silly idealTree ├── mime-types@2.1.14
64 silly idealTree ├── mime@1.3.4
64 silly idealTree ├── moment@2.17.1
64 silly idealTree ├── ms@0.7.2
64 silly idealTree ├── nan@2.5.1
64 silly idealTree ├── nearest-color@0.3.1
64 silly idealTree ├── node-opus@0.2.4
64 silly idealTree ├── nwmatcher@1.3.9
64 silly idealTree ├── oauth-sign@0.8.2
64 silly idealTree ├── ogg-packet@1.0.0
64 silly idealTree ├── options@0.0.6
64 silly idealTree ├── opusscript@0.0.1
64 silly idealTree ├── pako@1.0.4
64 silly idealTree ├── pinkie-promise@2.0.1
64 silly idealTree ├── pinkie@2.0.4
64 silly idealTree ├── process-nextick-args@1.0.7
64 silly idealTree ├── punycode@1.4.1
64 silly idealTree ├── qs@6.3.1
64 silly idealTree ├── readable-stream@2.2.2
64 silly idealTree ├── ref-struct@1.1.0
64 silly idealTree ├── ref@1.3.4
64 silly idealTree ├── request@2.79.0
64 silly idealTree ├── sntp@1.0.9
64 silly idealTree ├─┬ sshpk@1.10.2
64 silly idealTree │ └── assert-plus@1.0.0
64 silly idealTree ├── string_decoder@0.10.31
64 silly idealTree ├── stringstream@0.0.5
64 silly idealTree ├── strip-ansi@3.0.1
64 silly idealTree ├── superagent@3.4.4
64 silly idealTree ├── supports-color@2.0.0
64 silly idealTree ├── tough-cookie@2.3.2
64 silly idealTree ├── tunnel-agent@0.4.3
64 silly idealTree ├── tweetnacl@0.14.5
64 silly idealTree ├── ultron@1.0.2
64 silly idealTree ├── util-deprecate@1.0.2
64 silly idealTree ├── uuid@3.0.1
64 silly idealTree ├── verror@1.3.6
64 silly idealTree ├── writer.js@0.1.0
64 silly idealTree ├── ws@1.1.2
64 silly idealTree ├── xmlhttprequest@1.8.0
64 silly idealTree └── xtend@4.0.1
65 silly generateActionsToTake Starting
66 silly install generateActionsToTake
67 silly generateActionsToTake Finishing
68 silly diffTrees action count 1
69 silly diffTrees add contextify@0.1.15
70 silly decomposeActions action count 8
71 silly decomposeActions fetch contextify@0.1.15
72 silly decomposeActions extract contextify@0.1.15
73 silly decomposeActions test contextify@0.1.15
74 silly decomposeActions preinstall contextify@0.1.15
75 silly decomposeActions build contextify@0.1.15
76 silly decomposeActions install contextify@0.1.15
77 silly decomposeActions postinstall contextify@0.1.15
78 silly decomposeActions finalize contextify@0.1.15
79 silly runTopLevelLifecycles Starting
80 silly executeActions Starting
81 silly install executeActions
82 silly doSerial global-install 0
83 silly doParallel fetch 1
84 verbose correctMkdir /Users/LoganDark/.npm/_locks correctMkdir not in flight; initializing
85 verbose lock using /Users/LoganDark/.npm/_locks/staging-849df7126ed10aee.lock for /Users/LoganDark/node-selfbot/node_modules/.staging
86 silly doParallel extract 1
87 silly extract contextify@0.1.15
88 verbose unbuild node_modules/.staging/contextify-ea3638fe
89 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/.staging/contextify-ea3638fe is being purged from base /Users/LoganDark/node-selfbot
90 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/.staging/contextify-ea3638fe
91 verbose tar unpack /Users/LoganDark/.npm/contextify/0.1.15/package.tgz
92 verbose tar unpacking to /Users/LoganDark/node-selfbot/node_modules/.staging/contextify-ea3638fe
93 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/.staging/contextify-ea3638fe is being purged
94 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/.staging/contextify-ea3638fe
95 silly gunzTarPerm modes [ '755', '644' ]
96 silly gunzTarPerm extractEntry package.json
97 silly gunzTarPerm extractEntry .npmignore
98 silly gunzTarPerm extractEntry README.md
99 silly gunzTarPerm extractEntry .travis.yml
100 silly gunzTarPerm extractEntry LICENSE.txt
101 silly gunzTarPerm extractEntry .dntrc
102 silly gunzTarPerm extractEntry binding.gyp
103 silly gunzTarPerm extractEntry changelog
104 silly gunzTarPerm extractEntry lib/contextify.js
105 silly gunzTarPerm extractEntry test/contextify.js
106 silly gunzTarPerm extractEntry src/contextify.cc
107 silly gunzTarPerm extractEntry wscript
108 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/.staging/contextify-ea3638fe/node_modules is being purged
109 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/.staging/contextify-ea3638fe/node_modules
110 silly doParallel preinstall 1
111 silly preinstall contextify@0.1.15
112 info lifecycle contextify@0.1.15~preinstall: contextify@0.1.15
113 silly lifecycle contextify@0.1.15~preinstall: no script for preinstall, continuing
114 silly doReverseSerial remove 0
115 silly doSerial move 0
116 silly doSerial finalize 1
117 silly finalize /Users/LoganDark/node-selfbot/node_modules/contextify
118 silly doSerial build 1
119 silly build contextify@0.1.15
120 info linkStuff contextify@0.1.15
121 silly linkStuff contextify@0.1.15 has /Users/LoganDark/node-selfbot/node_modules as its parent node_modules
122 verbose linkBins contextify@0.1.15
123 verbose linkMans contextify@0.1.15
124 silly doSerial global-link 0
125 silly doParallel update-linked 0
126 silly doSerial install 1
127 silly install contextify@0.1.15
128 info lifecycle contextify@0.1.15~install: contextify@0.1.15
129 verbose lifecycle contextify@0.1.15~install: unsafe-perm in lifecycle true
130 verbose lifecycle contextify@0.1.15~install: PATH: /Users/LoganDark/.nvm/versions/node/v7.5.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/LoganDark/node-selfbot/node_modules/contextify/node_modules/.bin:/Users/LoganDark/node-selfbot/node_modules/.bin:/Users/LoganDark/.nvm/versions/node/v7.5.0/bin:/Users/LoganDark/.nvm/versions/node/v7.5.0/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
131 verbose lifecycle contextify@0.1.15~install: CWD: /Users/LoganDark/node-selfbot/node_modules/contextify
132 silly lifecycle contextify@0.1.15~install: Args: [ '-c', 'node-gyp rebuild' ]
133 silly lifecycle contextify@0.1.15~install: Returned: code: 1  signal: null
134 info lifecycle contextify@0.1.15~install: Failed to exec install script
135 verbose unlock done using /Users/LoganDark/.npm/_locks/staging-849df7126ed10aee.lock for /Users/LoganDark/node-selfbot/node_modules/.staging
136 silly rollbackFailedOptional Starting
137 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/contextify is being purged from base /Users/LoganDark/node-selfbot
138 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/contextify
139 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/contextify is being purged from base /Users/LoganDark/node-selfbot
140 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/contextify
141 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/contextify is being purged from base /Users/LoganDark/node-selfbot
142 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/contextify
143 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/contextify is being purged from base /Users/LoganDark/node-selfbot
144 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/contextify
145 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/contextify is being purged from base /Users/LoganDark/node-selfbot
146 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/contextify
147 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/contextify is being purged from base /Users/LoganDark/node-selfbot
148 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/contextify
149 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/contextify is being purged from base /Users/LoganDark/node-selfbot
150 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/contextify
151 silly gentlyRm /Users/LoganDark/node-selfbot/node_modules/contextify is being purged from base /Users/LoganDark/node-selfbot
152 verbose gentlyRm don't care about contents; nuking /Users/LoganDark/node-selfbot/node_modules/contextify
153 silly vacuum-fs purging /Users/LoganDark/node-selfbot/node_modules/contextify
154 silly vacuum-fs purging /Users/LoganDark/node-selfbot/node_modules/contextify
155 silly vacuum-fs purging /Users/LoganDark/node-selfbot/node_modules/contextify
156 silly vacuum-fs purging /Users/LoganDark/node-selfbot/node_modules/contextify
157 silly vacuum-fs purging /Users/LoganDark/node-selfbot/node_modules/contextify
158 silly vacuum-fs purging /Users/LoganDark/node-selfbot/node_modules/contextify
159 silly vacuum-fs purging /Users/LoganDark/node-selfbot/node_modules/contextify
160 silly vacuum-fs purging /Users/LoganDark/node-selfbot/node_modules/contextify
161 silly vacuum-fs quitting because other entries in /Users/LoganDark/node-selfbot/node_modules
162 silly vacuum-fs quitting because other entries in /Users/LoganDark/node-selfbot/node_modules
163 silly vacuum-fs quitting because other entries in /Users/LoganDark/node-selfbot/node_modules
164 silly vacuum-fs quitting because other entries in /Users/LoganDark/node-selfbot/node_modules
165 silly vacuum-fs quitting because other entries in /Users/LoganDark/node-selfbot/node_modules
166 silly vacuum-fs quitting because other entries in /Users/LoganDark/node-selfbot/node_modules
167 silly vacuum-fs quitting because other entries in /Users/LoganDark/node-selfbot/node_modules
168 silly vacuum-fs quitting because other entries in /Users/LoganDark/node-selfbot/node_modules
169 silly rollbackFailedOptional Finishing
170 silly runTopLevelLifecycles Finishing
171 silly install printInstalled
172 warn discord.js@11.0.0 requires a peer of uws@^0.12.0 but none was installed.
173 verbose If you need help, you may report this error at:
173 verbose     <https://github.com/npm/npm/issues>
174 warn logandark-selfbot@1.0.0 No repository field.
175 verbose If you need help, you may report this error at:
175 verbose     <https://github.com/npm/npm/issues>
176 verbose stack Error: contextify@0.1.15 install: `node-gyp rebuild`
176 verbose stack Exit status 1
176 verbose stack     at EventEmitter.<anonymous> (/Users/LoganDark/.nvm/versions/node/v7.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
176 verbose stack     at emitTwo (events.js:106:13)
176 verbose stack     at EventEmitter.emit (events.js:192:7)
176 verbose stack     at ChildProcess.<anonymous> (/Users/LoganDark/.nvm/versions/node/v7.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
176 verbose stack     at emitTwo (events.js:106:13)
176 verbose stack     at ChildProcess.emit (events.js:192:7)
176 verbose stack     at maybeClose (internal/child_process.js:890:16)
176 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
177 verbose pkgid contextify@0.1.15
178 verbose cwd /Users/LoganDark/node-selfbot
179 error Darwin 16.1.0
180 error argv "/Users/LoganDark/.nvm/versions/node/v7.5.0/bin/node" "/Users/LoganDark/.nvm/versions/node/v7.5.0/bin/npm" "install" "contextify"
181 error node v7.5.0
182 error npm  v4.1.2
183 error code ELIFECYCLE
184 error contextify@0.1.15 install: `node-gyp rebuild`
184 error Exit status 1
185 error Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
185 error Make sure you have the latest version of node.js and npm installed.
185 error If you do, this is most likely a problem with the contextify package,
185 error not with npm itself.
185 error Tell the author that this fails on your system:
185 error     node-gyp rebuild
185 error You can get information on how to open an issue for this project with:
185 error     npm bugs contextify
185 error Or if that isn't available, you can get their info via:
185 error     npm owner ls contextify
185 error There is likely additional logging output above.
186 verbose exit [ 1, true ]
```

I tried to find the repo for contextify. I tried.

**Comment by LoganDark** [comment]
And then, of course, I find [this](https://github.com/brianmcd/contextify/issues/205). Right after I posted the issue.
